Makefile, ci: Don't include embedded manpage in deb build
The previous commit failed with a strange error, so just give up for now:

    Exception occurred:
      File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
        self.searchpath = list(searchpath)
    TypeError: 'PosixPath' object is not iterable
    The full traceback has been saved in /tmp/sphinx-err-7d1f_wd9.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!